### ISSUE TITLE
Consider using webcrypto

### ISSUE THREAD

**Issue by rmhrisk** [aazcast/haciendacostarica-signer#2]
We created node-webcrypto-ossl originally but due to all of the issues we dealt with supporting native bindings to OpenSSL we later created a new library:
https://www.npmjs.com/package/@peculiar/webcrypto

Your scenario will work with this library and you will likely have fewer support issues with this package if you switch.

**Comment by aazcast** [comment]
Thanks for your help and suggestion, i change the library.
